name: django
channels:
  - defaults
dependencies:
  - asgiref=3.4.1
  - backcall=0.2.0
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - colorama=0.4.4
  - decorator=5.0.9
  - django=3.2.5
  - freetype=2.10.4
  - ipython=7.26.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jpeg=9b
  - libpng=1.6.37
  - libpq=12.2
  - libtiff=4.2.0
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.2
  - olefile=0.46
  - openssl=1.1.1l
  - parso=0.8.2
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.2
  - prompt-toolkit=3.0.17
  - psycopg2=2.8.6
  - pygments=2.10.0
  - python=3.9.5
  - pytz=2021.1
  - setuptools=52.0.0
  - sqlite=3.36.0
  - sqlparse=0.4.1
  - tk=8.6.10
  - traitlets=5.0.5
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - wheel=0.36.2
  - mysqlclient==2.0.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
      - boto==2.49.0
      - botocore==1.23.26
      - cffi==1.15.0
      - charset-normalizer==2.0.7
      - coreapi==2.3.3
      - coreschema==0.0.4
      - cryptography==36.0.0
      - defusedxml==0.7.1
      - django-background-tasks==1.2.5
      - django-compat==1.0.15
      - django-cors-headers==3.10.0
      - django-debug-toolbar==3.2.1
      - django-filter==21.1
      - django-storages==1.6.6
      - django-templated-mail==1.1.1
      - django-utils-six==2.0
      - djangorestframework==3.12.4
      - djangorestframework-simplejwt==4.8.0
      - djoser==2.1.0
      - docxcompose==1.3.3
      - docxtpl==0.12.0
      - drf-nested-routers==0.93.4
      - gunicorn==20.1.0
      - idna==3.3
      - itypes==1.2.0
      - jinja2==3.0.1
      - jmespath==0.10.0
      - lxml==4.6.3
      - markupsafe==2.0.1
      - oauthlib==3.1.1
      - pycparser==2.21
      - pyjwt==2.3.0
      - python-dateutil==2.8.2
      - python-docx==0.8.11
      - python3-openid==3.2.0
      - requests==2.26.0
      - requests-oauthlib==1.3.0
      - s3transfer==0.5.0
      - six==1.16.0
      - social-auth-app-django==4.0.0
      - social-auth-core==4.1.0
      - uritemplate==4.1.1
      - urllib3==1.26.7
      - pyyaml==6.0
      - qingstor-sdk==2.6.0
