# Generated by Django 3.2.5 on 2022-03-15 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='病人姓名')),
                ('sex', models.CharField(max_length=255, verbose_name='性别')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年龄')),
            ],
            options={
                'verbose_name': '病人',
                'verbose_name_plural': '病人集',
            },
        ),
        migrations.CreateModel(
            name='PathologyPictureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathologyPicture', models.FileField(upload_to='origin_images', verbose_name='病理图片')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='图片上传时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='图片描述')),
                ('isCutted', models.BooleanField(default=False, verbose_name='是否已经切图')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathologypictures', to='pathology.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '病理图片',
                'verbose_name_plural': '病理图片集',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='诊断创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='诊断更新时间')),
                ('regionPicture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='分子标记物表达图')),
                ('high', models.FloatField(default=1.0, verbose_name='高表达概率')),
                ('medium', models.FloatField(default=1.0, verbose_name='中表达概率')),
                ('low', models.FloatField(default=1.0, verbose_name='低表达概率')),
                ('advice', models.TextField(blank=True, null=True, verbose_name='肉眼病理所见')),
                ('pathologyPicture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pathology.pathologypictureitem', verbose_name='病理图片')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='pathology.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '诊断',
                'verbose_name_plural': '诊断集',
            },
        ),
    ]
