# Generated by Django 3.2.5 on 2022-03-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='patient',
        ),
    ]
