# Generated by Django 3.2.5 on 2022-03-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0002_remove_diagnosis_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='doctor_advice',
            field=models.TextField(blank=True, null=True, verbose_name='肉眼病理所见'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='advice',
            field=models.TextField(blank=True, null=True, verbose_name='临床意义判读'),
        ),
    ]
