# Generated by Django 3.2.5 on 2022-03-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0003_auto_20220315_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathologypictureitem',
            name='pathologyPicture',
            field=models.ImageField(upload_to='origin_images', verbose_name='病理图片'),
        ),
    ]
